name: CI
on: push
jobs:
  test:
    name: Test and check formatting
    runs-on: ubuntu-latest
    container: node:12
    steps:
      - uses: actions/checkout@master
      - name: Install dependencies
        run: yarn
      - name: Run the tests
        run: yarn test
      - name: Check code formatting
        run: yarn prettier
